#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/4a736c9b-f14c-41d9-9745-549705db46bd 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool Led;
  float temp;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include "DHT.h"

#define DHTPIN 9                          // defining the pin to which the temperature sensor is attached to the arduino
#define DHTTYPE DHT22                     // defining the sensor type. Here, it is DHT22
DHT dht(DHTPIN, DHTTYPE);                 // Initializing the DHT sensor
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  dht.begin();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  temp= dht.readTemperature();                              
  // storing the value of temperature in temp variable
  Serial.print("TEMPERATURE: ");
  Serial.print(temp);
  Serial.println("°C ");
  delay(3000);
}

void onLedChange() {
  // Do something
  digitalWrite(LED_BUILTIN, Led);                        
}


